# Theme
theme: jekyll-theme-minimal # https://github.com/pages-themes/minimal

# Site settings
title: docs@DanSpicyTaco
description: >
  personal notes: you are here! <br/>
  blog: <a href="https://medium.com/@danspicytaco">this way!</a> <br/>

  <br/><br/>
  ğŸ¤  ğŸŒ¶ï¸ ğŸŒ® ğŸ¤  ğŸŒ¶ï¸ ğŸŒ® ğŸ¤  ğŸŒ¶ï¸ ğŸŒ® ğŸ¤  ğŸŒ¶ï¸ ğŸŒ® 
  <br/><br/>
  <b>about me</b><br/>
  ğŸ“ robots + computers @ unsw <br/>
  ğŸ’» make websites, not war <br/>
  ğŸ³ï¸â€ğŸŒˆ open source software for all <br/>
